service: app
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-esbuild
  - serverless-offline

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi:
          path: /
          method: get
